### ISSUE TITLE
crashed on iOS 8 + C4 1.1.0 with CocoaPods

### ISSUE THREAD

**Issue by lufia** [C4Labs/C4iOS#676]
I'm not sure how to submit a issue to Spec repo of CocoaPods.

I'm using:
- Xcode 7.3.1
- C4 1.1.0 (Pods)
- CocoaPods 1.0.1

My app is workng on iOS 9.
But, on iOS 8, my app is crashed with logs:

```
dyld: Library not loaded: /System/Library/Frameworks/ReplayKit.framework/ReplayKit
  Referenced from: /path/to/myapp.app/Frameworks/C4.framework/C4
  Reason: image not found
```

Should _C4.podspec.json_ file link a ReplayKit as optional framework?

```
  "weak_frameworks": [
    "ReplayKit"
  ],
```

**Comment by C4Framework** [comment]
Hey Lufia,

Are you trying to use the ScreenRecorder in your app?

If not, you could potentially deselect the option to include the file from the app target: 

<img width="1043" alt="screen shot 2016-06-28 at 9 59 55 am" src="https://cloud.githubusercontent.com/assets/1447498/16424960/2413de1c-3d17-11e6-8ed4-b2495ce1b2b5.png">
(see the top right corner where the C4 target is deselected).

Or, remove the file completely if you don't plan to use it.

[ReplayKit is only available in iOS9+.](https://developer.apple.com/library/ios/documentation/ReplayKit/Reference/RPScreenRecorder_Ref/index.html#//apple_ref/occ/cl/RPScreenRecorder)

**Comment by C4Framework** [comment]
Hey Lufia, did you solve this?

**Comment by lufia** [comment]
Thank you for the notice.

I tried a solution works well.
So I deselect from target after `pod install`?

**Comment by lufia** [comment]
I will stop to support iOS 8 and so I deselect from app target during few days.

Thank you for your help.

**Comment by C4Framework** [comment]
Sorry, totally missed your question from Aug 19!
