### ISSUE TITLE
Xcode Version error

### ISSUE THREAD

**Issue by LoxiLichard** [C4Labs/C4iOS#680]
Excuse me.The Xcode version now is 7.2.But the C4.framework is  still work for 7.1.
When I  use the C4.framework,Xcode return many error.
I don't know how to deal with it.
could you give me a little help

**Comment by C4Framework** [comment]
Can you post a picture of your errors?
Or, even better, a link to the project that is generating the error?

Because, I am on Xcode version 7.3.1 with no errors.

**Comment by aleph7** [comment]
Over a year old, closing.
