### ISSUE TITLE
What to do when refactor from an older version to the latest and greatest ?

### ISSUE THREAD

**Issue by KoertGaaikema** [C4Labs/C4iOS#684]
I have to refactor a project with old version of the framework ( still with the C4 prefixes ) to the latest  version. 

My main question now is this : 
There are some classes that extended C4view 
When I try to remove the C4 prefix I get this error 
_......./ConnectingView.swift:14:7: Cannot inherit from non-open class 'View' outside of its defining module_ 

How should I refactor the old C4View classes ?

k.

**Comment by KoertGaaikema** [comment]
update : I changed the C4 view class to Open instead of Public. This seems to work.

My next issue is that the TextShape is causing problems. even with the default font I get this error : 

fatal error: unexpectedly found nil while unwrapping an Optional value

this happens in the createTextPath.swift file on line 110 :
textPath.addPath(glyphPath!, transform: translation) 

Any clues ?

K.

**Comment by C4Framework** [comment]
Hey Koert. 
I can help better if I can see your project, is it available somewhere?
`C4`-prefixes are definitely old :)

**Comment by KoertGaaikema** [comment]
Hi,
I figured it out. I was using cocoa pods to get the latest version. But that didn't include the last commit that fixes the issue :)

**Comment by C4Framework** [comment]
Great!
