### ISSUE TITLE
Package installer issue

### ISSUE THREAD

**Issue by noisyneuron** [C4Labs/C4iOS#687]
After installing the package, I don't see the project in the xcode window, nor can I seem to find it anywhere.. 

os x v10.10.5
xcode v7.2.1

What is the default install location? Any suggestions?

**Comment by C4Framework** [comment]
Hey @noisyneuron I just confirmed on my setup that it works:

OSX 10.12.6
Xcode 8.8.3

The last update for the installer involved new code that works only for Swift 3 / Xcode 8+.

If you can't update to Sierra / Xc8, you can try: http://www.c4ios.com/C4Installer_1_1_0.pkg

This is an older version of the installer that should work on your system.

**Comment by noisyneuron** [comment]
Still no luck... can't find the project anywhere..

**Comment by C4Framework** [comment]
If you want to join our slack channel we can chat directly about it, and hopefully I can help you get it running.

https://join-c4.herokuapp.com/

**Comment by aleph7** [comment]
Over a year old, closing.
