### ISSUE TITLE
Overlapping Access to 'N' Error

### ISSUE THREAD

**Issue by C4Framework** [C4Labs/C4iOS#689]
When compiling C4iOS in Xcode 9, the following code generates an error in `

Transform.swift`:

```
    // LU factorisation
    dgetrf_(&N, &N, &matrix, &N, &pivot, &error)
    if error != 0 {
        return nil
    }

    // matrix inversion
    var workspace = [__CLPK_doublereal](repeating: 0, count: 4)
    dgetri_(&N, &matrix, &N, &pivot, &workspace, &N, &error)
    if error != 0 {
        return nil
    }
```

Error Message: 
```Overlapping accesses to 'N', but modification requires exclusive access; consider copying to a local variable```

<img width="1395" alt="screen shot 2017-09-15 at 4 55 06 pm" src="https://user-images.githubusercontent.com/1447498/30507156-ae5f626c-9a36-11e7-9a8e-36829c0e69f1.png">

**Comment by aleph7** [comment]
Fixed in 5a1344c649360020f614fb097185d3c922a149b7
